name: CCM Integration tests

on:
  push:
    branches:
     - master
     - next
     - docker-ccm

  pull_request:
    branches:
     - docker-ccm
     - next

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        sudo apt-get install -y openjdk-8-jdk rpm2cpio
        pip install -U pip setuptools pytest
        python setup.py install
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
 
    - name: Download versions
      run: |
        ./ccm create temp -n 1 --scylla --version unstable/master:2020-10-25T21%3A55%3A10Z > /dev/null
        ./ccm remove
        ./ccm create temp-cas -n 1 --version 3.11.4 > /dev/null
        ./ccm remove
        docker pull scylladb/scylla-nightly:666.development-0.20201015.8068272b466

    - name: Test with pytest
      run: |
        python -m pytest ./tests
